# Generated by Django 4.1.7 on 2023-02-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeniItem',
            new_name='MenuItem',
        ),
    ]
